--- 
- name: Build simple nodejs app
  hosts: tag_Environment_Testing
  become: yes
  tasks:
    - name: Ensure nodejs and git are installed
      package:
        name: 
          - git
          - nodejs
        state: present

    - name: Create folder to checkout code 
      file:
        path: ~/simple-demo-app
        state: directory 

    - name: checkout code
      git:
        repo: https://github.com/corumj/simple-demo-app
        dest: ~/simple-demo-app
        force: yes

    - name: install node dependencies
      community.general.npm:
        path: ~/simple-demo-app
    
    - name: Run NPM audit and force fix dependencies
      command:
        chdir: "/root/simple-demo-app/"
        cmd: "npm audit fix --force"
