---
- name: Deploy application
  hosts: tag_Environment_Testing
  become: yes
  gather_facts: yes
  tasks:
    - name: Copy app systemd file to /tmp
      ansible.posix.synchronize:
        src: "srv/dcmetromap.service"
        dest: "/tmp/dcmetromap.service"

    - name: Install systemd unit file
      command: mv /tmp/dcmetromap.service /etc/systemd/system/dcmetromap.service
    
    - name: set perms
      command: chown root:root /etc/systemd/system/dcmetromap.service

    - name: enable and start service
      systemd:
        name: dcmetromap
        daemon_reload: yes
        enabled: yes
        state: started

    - name: Provide URL to test app
      debug:
        msg: "http://{{ ansible_host }}/"
