---
- name: Deploy application
  hosts: tag_Environment_Testing
  become: yes
  gather_facts: yes
  tasks:
    - name: Copy app systemd file to /etc/systemd/system
      copy:
        src: srv/dcmetromap.service
        dest: /root/dcmetromap.service
        owner: root
        group: root

#    - name: enable and start service
#      systemd:
#        name: dcmetromap
#        daemon_reload: yes
#        enabled: yes
#        state: started
#
#    - name: Provide URL to test app
#      debug:
#        msg: "http://{{ ansible_host }}/"
