---
- name: Provision instance to deploy app
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    key_name: ansibledemo
    image: ami-096fda3c22c1c990a
    id: "demo-app"
    sec_group: "{{ id }}-sec"
  tasks:
    - name: Get Instance facts 
      block:
        - name: Get Instances facts
          community.aws.ec2_instance_info:
            aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
            aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
            region: "{{ region }}"
          register: result

        - name: Instance id
          debug:
            msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
          loop: "{{ result.instances }}"

      tags: always 

    - name: Provision EC2 Instances
      block:
        - name: Provision instance(s)
          community.aws.ec2_instance:
            state: present
            aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
            aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
            key_name: mhermans-key
            name: "{{ id }}"
            security_group: default
            image_id: "{{ image }}"
            instance_type: t2.micro
            region: "{{ region }}"
            tags:
              Environment: Testing
          
      tags: ['never', 'provision']

    - name: Deprovision ec2 instance
      block:
        - name: Remove EC2 Instance 
          community.aws.ec2_instance:
            state: absent
            region: "{{ region }}"
            aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
            aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
            filters:
              tag:Environment: Testing

      tags: ['never', 'deprovision']
